Repository mathieusporta/product-locator, pull requests merged in 2020-11, with the labels that each got.

#12 init project with mongodb
  .env
  package.json
  pages/index.tsx
  src/database.ts
  yarn.lock
Labels: back

#13 shop with div rayon
  pages/index.tsx
  src/database.ts
  styles/globals.css
Labels: back

#14 layout_header
  components/header.tsx
  components/layout.tsx
  pages/index.tsx
Labels: back

#15 bug fix
  pages/index.tsx
Labels: bug

#17 searchbarre
  components/SearchBarSection.tsx
  components/layout.tsx
  pages/_app.tsx
  styles/SearchBar.css
Labels: back

#20 Search bar configuration
  src/components/header.tsx
  src/pages/index.tsx
  src/pages/magasins.tsx
Labels: back

#28 decoupage avec les composants
  src/components/SearchBarSection.tsx
  src/components/header.tsx
  src/components/layout.tsx
  src/components/magasin.tsx
  src/components/pagination.tsx
  src/components/tableauProduits.tsx
  src/pages/listeProduits.tsx
  src/pages/magasins.tsx
Labels: back

#29 oauth2 google
  package.json
  public/styles/globals.css
  src/components/header.tsx
  src/pages/api/auth/[...nextauth].js
  yarn.lock
Labels: back, enhancement

#31 onclik sur tableau
  public/styles/globals.css
  src/components/header.tsx
  src/components/magasin.tsx
  src/components/tableauProduits.tsx
  src/pages/api/auth/[...nextauth].tsx
  src/pages/listeProduits.tsx
Labels: back

#33 fix de bug
  src/pages/api/auth/[...nextauth].js
  src/pages/api/auth/[...nextauth].tsx
Labels: bug

#36 update product in mongodb
  package.json
  src/components/tableauProduitsAdmin.tsx
  src/pages/admin/admin.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/create/newProduct.ts
  src/pages/api/search.tsx
  src/pages/api/update/updateProduct.ts
  src/pages/update/[update].tsx
  yarn.lock
Labels: back

#37 ajout du btn delete
  src/components/tableauProduitsAdmin.tsx
  src/pages/api/delete/deleteProduct.ts
  src/pages/create/newProduct.tsx
  src/pages/delete/[delete].tsx
Labels: back, dev, enhancement
